# Generated by Django 2.2.2 on 2019-07-19 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['created', 'owner']},
        ),
    ]
